"""Beginner-friendly vocabulary & phrase notes for dialogue breakdown."""

from get_episode_vocab import GET_GRAMMAR_PATTERNS, GET_PHRASE_NOTES, GET_SENTENCE_VI

# Multi-word phrases — matched longest first
PHRASE_NOTES: dict[str, str] = {
    "more affordable": "rẻ hơn / dễ chi trả hơn — affordable = giá vừa túi tiền",
    "more expensive": "đắt hơn — expensive = đắt",
    "farther away": "xa hơn — farther = khoảng cách xa hơn (so sánh)",
    "further away": "xa hơn (tương tự farther)",
    "close to the station": "gần ga tàu — tiện đi làm",
    "close to": "gần với",
    "makes more sense": "hợp lý hơn / có lý hơn",
    "makes sense": "hợp lý / có lý",
    "torn between": "phân vân giữa hai lựa chọn",
    "leaning toward": "đang nghiêng về / có xu hướng chọn",
    "weigh up": "cân nhắc ưu nhược điểm",
    "getting used to": "đang quen dần với",
    "walk me through": "giải thích từng bước cho tôi",
    "walk you through": "giải thích từng bước cho bạn",
    "let me walk you through": "để tôi giải thích từng bước",
    "could you help me": "bạn giúp tôi được không",
    "help me with": "giúp tôi việc / phần",
    "look forward to": "mong chờ / hướng tới",
    "step by step": "từng bước một",
    "root cause": "nguyên nhân gốc",
    "more sense to me": "hợp lý hơn với tôi",
    "great options": "những lựa chọn tốt",
    "near tokyo": "gần Tokyo",
    "commute time": "thời gian đi làm (commute = đi lại hàng ngày)",
    "rent and commute": "tiền thuê nhà và thời gian đi làm",
    "cheaper one": "căn rẻ hơn",
    "this apartment": "căn hộ này",
    "this place": "chỗ này / căn này",
    "option a": "phương án A",
    "option b": "phương án B",
    "the station": "ga tàu",
    "daily life": "đời sống hàng ngày",
    "fill out": "điền (form)",
    "running late": "đang bị trễ",
    "would it be possible": "liệu có thể... không (lịch sự)",
    "tell me about a time": "hãy kể về một lần khi",
    "it seems like": "có vẻ như",
    "the issue is that": "vấn đề là",
    "i think we should": "tôi nghĩ chúng ta nên",
    "that makes sense": "điều đó hợp lý",
    "see your point": "tôi hiểu ý bạn",
    "follow up": "theo dõi / nhắc lại",
    "loop me in": "cho tôi vào luồng thông tin",
    "get back to": "phản hồi lại sau",
    "check in on": "hỏi thăm / cập nhật về",
    "more than": "hơn (so sánh)",
    "less than": "ít hơn",
    "go with": "chọn (một phương án)",
    "sleep on it": "để qua đêm suy nghĩ rồi quyết",
    "rule out": "loại trừ (một phương án)",
    "stick with": "giữ nguyên / bám theo",
    "push back": "phản hồi / từ chối nhẹ",
    "outside the scope": "ngoài phạm vi công việc",
}

# Single words — for token-by-token breakdown
WORD_NOTES: dict[str, str] = {
    "affordable": "giá phù hợp túi tiền / không quá đắt",
    "expensive": "đắt",
    "cheaper": "rẻ hơn (cheap + er)",
    "farther": "xa hơn (khoảng cách — farther)",
    "further": "xa hơn / thêm nữa",
    "closer": "gần hơn",
    "station": "ga tàu / bến xe",
    "apartment": "căn hộ",
    "rent": "tiền thuê nhà",
    "commute": "đi làm hàng ngày (đi lại)",
    "options": "các lựa chọn",
    "option": "lựa chọn / phương án",
    "agent": "nhân viên môi giới / đại lý",
    "contract": "hợp đồng",
    "landlord": "chủ nhà cho thuê",
    "deposit": "tiền đặt cọc",
    "utilities": "tiền điện nước gas",
    "neighborhood": "khu phố / vùng lân cận",
    "balcony": "ban công",
    "compare": "so sánh",
    "decision": "quyết định",
    "torn": "phân vân (torn between = kẹt giữa hai lựa chọn)",
    "leaning": "nghiêng về / có xu hướng",
    "weigh": "cân / cân nhắc (weigh up = cân nhắc kỹ)",
    "sense": "lý / ý nghĩa (make sense = hợp lý)",
    "through": "xuyên suốt / từng bước (walk through)",
    "afford": "đủ khả năng chi trả",
    "tokyo": "Tokyo — thủ đô Nhật Bản",
    "japan": "Nhật Bản",
    "great": "tuyệt / tốt",
    "near": "gần",
    "away": "xa (ở khoảng cách)",
    "but": "nhưng",
    "because": "bởi vì",
    "place": "chỗ / nơi",
    "think": "nghĩ",
    "need": "cần",
    "help": "giúp đỡ",
    "could": "có thể (lịch sự hơn can)",
    "would": "sẽ / dùng để hỏi lịch sự",
    "should": "nên",
    "deploy": "triển khai code lên server",
    "refactor": "viết lại code cho sạch hơn",
    "patch": "bản vá — sửa nhanh tạm thời",
    "rollback": "quay lại bản code cũ",
    "bug": "lỗi phần mềm",
    "api": "giao diện lập trình (API)",
    "cache": "bộ nhớ đệm",
    "confirm": "xác nhận",
    "checkout": "thanh toán / giỏ hàng",
    "flow": "luồng / quy trình",
    "affects": "ảnh hưởng (động từ)",
    "incident": "sự cố",
    "deadline": "hạn chót",
    "scope": "phạm vi công việc",
    "salary": "lương",
    "interview": "phỏng vấn",
    "recruiter": "nhân viên tuyển dụng",
    "demo": "buổi demo / trình diễn sản phẩm",
    "investor": "nhà đầu tư",
    "monitoring": "giám sát hệ thống",
    "postmortem": "buổi phân tích sau sự cố",
    "shrine": "đền thờ Nhật",
    "onsen": "suối nước nóng Nhật",
    "konbini": "cửa hàng tiện lợi Nhật",
    "train": "tàu",
    "taxi": "taxi",
    "hotel": "khách sạn",
    "itinerary": "lịch trình du lịch",
    "order": "gọi món / đặt hàng",
    "menu": "thực đơn",
    "receipt": "hóa đơn / biên lai",
    "form": "mẫu đơn / form",
    "appointment": "cuộc hẹn",
    "clinic": "phòng khám",
    "bank": "ngân hàng",
    "account": "tài khoản",
    "moving": "chuyển nhà / dọn",
    "excited": "hào hứng / phấn khích",
    "nervous": "lo lắng / hồi hộp",
    "worried": "lo âu",
    "surprised": "ngạc nhiên",
    "glad": "vui / mừng",
    "proud": "tự hào",
    "thank": "cảm ơn",
    "sorry": "xin lỗi",
    "please": "làm ơn / xin vui lòng",
    "more": "hơn (dùng trong so sánh: more + tính từ)",
    "most": "nhất (so sánh nhất)",
    "better": "tốt hơn",
    "worse": "tệ hơn",
    "than": "hơn (so sánh: cheaper than)",
    "if": "nếu",
    "when": "khi",
    "where": "ở đâu / nơi mà",
    "what": "gì / cái gì",
    "how": "như thế nào",
    "why": "tại sao",
    "who": "ai",
    "this": "này / cái này",
    "that": "đó / cái đó",
    "these": "những cái này",
    "those": "những cái đó",
    "here": "ở đây",
    "there": "ở đó",
    "today": "hôm nay",
    "tomorrow": "ngày mai",
    "yesterday": "hôm qua",
    "time": "thời gian",
    "money": "tiền",
    "work": "làm việc / công việc",
    "team": "team / nhóm",
    "meeting": "cuộc họp",
    "email": "email / thư điện tử",
    "message": "tin nhắn",
    "reply": "trả lời",
    "update": "cập nhật",
    "fix": "sửa / fix lỗi",
    "release": "phát hành / release sản phẩm",
    "test": "kiểm thử / test",
    "review": "xem xét / review",
    "feedback": "phản hồi",
    "support": "hỗ trợ",
    "question": "câu hỏi",
    "answer": "câu trả lời",
    "problem": "vấn đề",
    "solution": "giải pháp",
    "idea": "ý tưởng",
    "plan": "kế hoạch",
    "schedule": "lịch / sắp xếp thời gian",
    "possible": "có thể",
    "available": "có sẵn / rảnh",
    "ready": "sẵn sàng",
    "sure": "chắc chắn",
    "maybe": "có lẽ",
    "probably": "có lẽ / khả năng cao",
    "definitely": "chắc chắn / nhất định",
    "actually": "thực ra",
    "really": "thật sự / rất",
    "very": "rất",
    "too": "quá (too expensive = quá đắt)",
    "also": "cũng",
    "still": "vẫn / còn",
    "already": "đã / rồi",
    "just": "vừa mới / chỉ",
    "only": "chỉ / duy nhất",
    "first": "đầu tiên / trước hết",
    "next": "tiếp theo",
    "last": "cuối cùng",
    "before": "trước",
    "after": "sau",
    "during": "trong lúc",
    "while": "trong khi",
    "until": "cho đến khi",
    "since": "từ khi / vì",
    "about": "về / khoảng",
    "with": "với",
    "without": "không có",
    "from": "từ",
    "into": "vào trong",
    "between": "giữa",
    "among": "trong số",
    "over": "qua / hơn",
    "under": "dưới",
    "again": "lại / lần nữa",
    "always": "luôn luôn",
    "never": "không bao giờ",
    "sometimes": "đôi khi",
    "often": "thường xuyên",
    "usually": "thường / thông thường",
}

# Full-sentence translations (longest match first) — slug or substring
SENTENCE_VI: dict[str, str] = {
    "here are two great options near tokyo": "Đây là hai lựa chọn tuyệt gần Tokyo!",
    "option a is close to the station, but it's more expensive": "Căn A gần ga tàu, nhưng đắt hơn.",
    "option b is more affordable, but farther away": "Căn B rẻ hơn, nhưng xa hơn.",
    "option a is close to the station but it's more expensive option b is more affordable but farther away": "Căn A gần ga nhưng đắt hơn. Căn B rẻ hơn nhưng xa hơn.",
    "option a is close to the station but more expensive option b is more affordable but farther away": "Căn A gần ga nhưng đắt hơn. Căn B rẻ hơn nhưng xa hơn.",
    "i'm torn between this apartment and the cheaper one": "Tôi phân vân giữa căn hộ này và căn rẻ hơn.",
    "i'm leaning toward this place because it's close to the station": "Tôi đang nghiêng về căn này vì nó gần ga tàu.",
    "we need to weigh up rent and commute time": "Chúng ta cần cân nhắc tiền thuê và thời gian đi làm.",
    "this apartment makes more sense to me": "Căn hộ này hợp lý hơn với tôi.",
    "how is life in tokyo going": "Cuộc sống ở Tokyo thế nào rồi?",
    "could you help me with this": "Bạn giúp tôi việc này được không?",
    "let me walk you through it": "Để tôi giải thích từng bước cho bạn.",
    "i'm getting used to life in japan": "Tôi đang quen dần với cuộc sống ở Nhật.",
    "that makes sense now — thank you": "Giờ tôi hiểu rồi — cảm ơn bạn.",
    "that makes sense now - thank you": "Giờ tôi hiểu rồi — cảm ơn bạn.",
}
SENTENCE_VI.update(GET_SENTENCE_VI)
PHRASE_NOTES.update(GET_PHRASE_NOTES)

# Canonical dialogue: data/canonical-dialogues.json (scripts/build-canonical-dialogues.py)

GRAMMAR_PATTERNS = [
    (r"\bmore (\w+)\b", "So sánh hơn: **more + tính từ** = ... hơn (more affordable = rẻ hơn, more expensive = đắt hơn)."),
    (r"\b(\w+)er\b", "So sánh ngắn: thêm **-er** = ... hơn (cheaper = rẻ hơn, closer = gần hơn)."),
    (r"\bfarther\b", "**farther** = xa hơn (nói về khoảng cách địa lý)."),
    (r"\bbut\b", "**but** = nhưng — nối hai ý trái ngược (gần ga **nhưng** đắt)."),
    (r"\bbecause\b", "**because** = bởi vì — giải thích lý do."),
    (r"\bclose to\b", "**close to** = gần với (close to the station = gần ga)."),
    (r"\btorn between\b", "**torn between A and B** = phân vân giữa A và B."),
    (r"\bleaning toward\b", "**leaning toward** = đang nghiêng về / có xu hướng chọn."),
    (r"\bweigh up\b", "**weigh up** = cân nhắc kỹ ưu và nhược điểm."),
    (r"\bmakes? more sense\b", "**make(s) more sense** = hợp lý hơn / có lý hơn."),
    (r"\bcould you\b", "**Could you + V?** = bạn có thể... không? (lịch sự hơn Can you)."),
    (r"\bcan you\b", "**Can you + V?** = bạn có thể... không?"),
    (r"\blet's\b", "**Let's + V** = chúng ta hãy... (đề xuất làm chung)."),
    (r"\blet me\b", "**Let me + V** = để tôi... (tự đề nghị làm giúp)."),
    (r"\bit's\b", "**it's** = it is = nó là / đó là."),
    (r"\bi'm\b", "**I'm** = I am = tôi đang / tôi là."),
    (r"\bwe're\b", "**we're** = we are = chúng ta đang."),
    (r"\bdon't\b", "**don't** = do not = không (phủ định)."),
    (r"\bcan't\b", "**can't** = cannot = không thể."),
    (r"\bgetting used to\b", "**getting used to + N/V-ing** = đang quen dần với."),
]
GRAMMAR_PATTERNS.extend(GET_GRAMMAR_PATTERNS)
