"""Vocabulary, translations, and grammar hints for Get Phrasal arcs (eps 105–118)."""

import re


def _normalize_match(text: str) -> str:
    """Match dialogue_helpers.normalize_match without circular import."""
    t = (text or "").lower().replace("\u2019", "'").replace("\u2018", "'")
    t = re.sub(r"\s+", " ", t.strip().rstrip(".!?"))
    t = re.sub(r"[^\w\s']", " ", t)
    return re.sub(r"\s+", " ", t).strip()


_RAW_SENTENCE_PAIRS: list[tuple[str, str]] = [
    # 105
    ("Welcome! I'll get you looped in on the launch channel.", "Chào mừng! Tôi sẽ thêm bạn vào kênh launch."),
    ("Sorry — I keep getting pinged on every thread.", "Xin lỗi — tôi cứ bị ping trên mọi thread."),
    ("Don't worry. We'll get you up to speed by standup tomorrow.", "Đừng lo. Chúng tôi sẽ giúp bạn nắm bắt nhanh trước standup ngày mai."),
    ("There are twelve stakeholders I wasn't looped in on yet.", "Có mười hai stakeholder mà tôi chưa được loop in."),
    ("I'm getting up to speed — but I still get pinged after hours.", "Tôi đang nắm bắt dần — nhưng vẫn bị ping sau giờ làm. (Panel 5 — PM thêm: «That's startup life.» = Đó là kiểu startup.)"),
    ("Next: We Need Buy-In", "Tiếp theo: We Need Buy-In"),
    # 106
    ("We can't ship without buy-in from design and legal.", "Chúng ta không thể ship nếu chưa có buy-in từ design và legal."),
    ("We're not aligned on the user flow yet.", "Chúng ta chưa thống nhất về user flow."),
    ("Let's get aligned on one MVP before we debate polish.", "Hãy thống nhất một MVP trước khi tranh luận polish."),
    ("If we get buy-in on this scope, we can get the ball rolling Monday.", "Nếu có buy-in với scope này, thứ Hai ta khởi động được."),
    ("I'm in.", "Tôi đồng ý. (Panel 5 — PM thêm: «Finally aligned — ship week, here we come.» = Cuối cùng cũng thống nhất — tuần ship đây rồi.)"),
    ("Next: Blocked on Dependencies", "Tiếp theo: Blocked on Dependencies"),
    # 107
    ("I'm blocked on the payments API — third day.", "Tôi bị blocked ở payments API — ngày thứ ba rồi."),
    ("Every time I ask, I get blocked on a different dependency.", "Mỗi lần hỏi, tôi lại bị kẹt ở một dependency khác."),
    ("Nam needs to get unblocked today — demo is Friday.", "Nam cần được gỡ block hôm nay — demo thứ Sáu."),
    ("You should be unblocked now — try the staging key.", "Giờ bạn nên unblocked rồi — thử staging key đi."),
    ("Once I'm unblocked, I can get through code review tonight.", "Khi unblocked, tối nay tôi vượt qua code review được. (Panel 5 — Aoi: «Last gate before ship day.» = Cổng cuối trước ngày ship.)"),
    ("Next: Ship It Friday", "Tiếp theo: Ship It Friday"),
    # 108
    ("We need sign-off from QA and product before we get shipped.", "Cần sign-off từ QA và product trước khi được ship."),
    ("Staging looks good — I'll get sign-off from QA in ten minutes.", "Staging ổn — tôi lấy sign-off QA trong mười phút."),
    ("Are we ready? I want everything to get ready before we merge.", "Sẵn sàng chưa? Tôi muốn mọi thứ ready trước khi merge."),
    ("Feature got shipped — nice work.", "Feature đã shipped — làm tốt lắm. (Panel 4 — PM thêm: «Sign-off, shipped, and we still have Friday night.» = Sign-off, shipped, và vẫn còn tối thứ Sáu.)"),
    ("Next: Pulled Into the War Room", "Tiếp theo: Pulled Into the War Room"),
    # 109
    ("Sorry — you're getting pulled into the checkout war room.", "Xin lỗi — bạn đang bị kéo vào war room checkout."),
    ("I'm stuck — the error only happens in prod, not staging.", "Tôi bị kẹt — lỗi chỉ xảy ra trên prod, không phải staging."),
    ("Don't spin — tell PM you'll get back to them in thirty minutes.", "Đừng xoay vòng — báo PM bạn sẽ phản hồi trong ba mươi phút."),
    ("I'll get back to the team once rollback is confirmed.", "Tôi sẽ phản hồi team khi rollback được xác nhận."),
    ("Got pulled into my first war room — and we got through it.", "Lần đầu bị kéo vào war room — và chúng ta vượt qua được. (Panel 5 — PM: «Thanks for getting back to us.» = Cảm ơn vì đã phản hồi.)"),
    ("Next: The Acquisition News", "Tiếp theo: The Acquisition News"),
    # 110
    ("Big news — we're getting acquired by a global platform.", "Tin lớn — công ty mình sắp bị mua bởi nền tảng toàn cầu."),
    ("Does this mean layoffs… or opportunities?", "Điều này có nghĩa sa thải… hay cơ hội?"),
    ("I wanted face time with you before the reorg.", "Tôi muốn có face time với bạn trước đợt tái cơ cấu."),
    ("You're getting promoted to senior — they noticed your ship work.", "Bạn sắp được thăng senior — họ để ý việc ship của bạn."),
    ("When a startup gets acquired, culture changes — stay flexible.", "Khi startup bị mua, văn hóa thay đổi — hãy linh hoạt."),
    ("I got face time, got promoted… and the whole company got acquired.", "Tôi có face time, được thăng chức… và cả công ty bị mua."),
    # 111
    ("Welcome! Let's get to the hotel before rush hour.", "Chào mừng! Mình đến khách sạn trước giờ cao điểm nhé."),
    ("I'll get you checked in — passport and booking, please.", "Tôi làm check-in cho bạn — hộ chiếu và booking, làm ơn."),
    ("Walk with me — you'll get your bearings in the old town.", "Đi cùng tôi — bạn sẽ định hướng được ở phố cổ."),
    ("It took an hour to get to Zurich, but I already love it.", "Mất một giờ để đến Zurich, nhưng tôi đã yêu nơi này."),
    ("Once I get my bearings, I want to explore every alley.", "Khi định hướng xong, tôi muốn khám phá từng ngõ."),
    ("Next: The Glacier Express", "Tiếp theo: The Glacier Express"),
    # 112
    ("How do I get a ticket for the Glacier Express?", "Làm sao mua vé Glacier Express?"),
    ("First class or second? Get a ticket with a seat reservation.", "Hạng nhất hay nhì? Mua vé kèm đặt chỗ."),
    ("Wait — do we get on at platform 7 or 8?", "Khoan — mình lên tàu ở sân ga 7 hay 8?"),
    ("We get off at Filisur — don't miss the stop.", "Chúng ta xuống ở Filisur — đừng lỡ ga."),
    ("I nearly forgot to get off — the view hypnotized me.", "Suýt quên xuống — cảnh làm tôi mê luôn."),
    ("Next: View from the Top", "Tiếp theo: View from the Top"),
    # 113
    ("From here you'll get a view of the whole Bernese Alps.", "Từ đây bạn nhìn thấy cả dãy Bernese Alps."),
    ("I think I'm getting altitude sickness — head is spinning.", "Hình như tôi bị say độ cao — đầu chóng mặt."),
    ("Sit still. Altitude sickness passes if you rest.", "Ngồi yên. Say độ cao sẽ qua nếu nghỉ ngơi."),
    ("Can I get change for this twenty-franc note?", "Đổi tiền lẻ cho tờ hai mươi franc được không?"),
    ("Worth it — I got a view of mountains I'll never forget.", "Đáng giá — tôi có cảnh núi không quên được."),
    ("Next: Snowed In at Zermatt", "Tiếp theo: Snowed In at Zermatt"),
    # 114
    ("You might get snowed in tonight — roads are closing.", "Đêm nay có thể bị kẹt tuyết — đường đang đóng."),
    ("We got held up by the avalanche warning.", "Chúng ta bị trì hoãn vì cảnh báo lở tuyết."),
    ("We can get by with phrasebook German and gestures.", "Ta xoay xở được bằng sách cụm từ tiếng Đức và điệu bộ."),
    ("English gets you by here — everyone is kind.", "Tiếng Anh giúp bạn xoay xở ở đây — mọi người đều tử tế."),
    ("Sometimes getting held up is how you meet the best stories.", "Đôi khi bị trì hoãn là cách gặp câu chuyện hay nhất."),
    ("Next: Lost on the Alpine Trail", "Tiếp theo: Lost on the Alpine Trail"),
    # 115
    ("Stay close — it's easy to get lost up here.", "Ở gần nhé — dễ lạc lắm ở đây."),
    ("I think we're lost — which way back to Zermatt?", "Hình như mình lạc — về Zermatt hướng nào?"),
    ("Listen — we got swept up in a local festival by accident.", "Nghe kìa — mình bị cuốn vào lễ hội làng tình cờ."),
    ("Best wrong turn ever — I got swept up in the music.", "Rẽ nhầm tuyệt vời nhất — tôi cuốn vào nhịp nhạc."),
    ("I can get you a ride back — jump in the back.", "Tôi chở bạn về — nhảy lên thùng xe."),
    ("Switzerland taught me how to get around — even when lost.", "Thụy Sĩ dạy tôi đi lại — kể cả khi lạc."),
    # 116
    ("I need to get ready — deep breath.", "Tôi cần chuẩn bị tinh thần — hít thở sâu."),
    ("It takes time to get used to speaking English out loud.", "Cần thời gian để quen nói tiếng Anh to ra."),
    ("Sorry — I'm not used to talking this long in English.", "Xin lỗi — tôi chưa quen nói tiếng Anh lâu thế này."),
    ("You got through the hardest part — the first five minutes.", "Bạn vượt qua phần khó nhất — năm phút đầu."),
    ("I got through my first meetup without switching to Vietnamese.", "Tôi vượt qua buổi meetup đầu mà không chuyển sang tiếng Việt."),
    ("Next: When You Finally Get It", "Tiếp theo: When You Finally Get It"),
    # 117
    ("Don't memorize lists — use them until you get it.", "Đừng học thuộc danh sách — dùng đến khi hiểu."),
    ("Oh — I get it now. Get blocked means dependency stopped me.", "Ồ — tôi hiểu rồi. Get blocked nghĩa là dependency chặn tôi."),
    ("Let me get back to you after this lesson — I'm studying.", "Để tôi phản hồi sau buổi học — tôi đang học."),
    ("Your English is good — you get by fine here.", "Tiếng Anh bạn tốt — bạn xoay xở ổn ở đây."),
    ("I used to get by with one-word answers. Not anymore.", "Trước tôi xoay xở bằng câu một từ. Giờ không còn."),
    ("Next: Everyday Get Finale", "Tiếp theo: Everyday Get Finale"),
    # 118
    ("I'll get you onboarded — same as my SF rotation.", "Tôi sẽ onboard bạn — giống rotation SF của tôi."),
    ("We need your sign-off as his onboarding buddy.", "Cần sign-off của bạn với vai trò onboarding buddy."),
    ("Get looped in, get unblocked, get shipped — you'll hear these daily.", "Get looped in, get unblocked, get shipped — bạn sẽ nghe mỗi ngày."),
    ("Can I get a ride to the station with you?", "Tôi nhờ bạn chở đến ga được không?"),
    ("I got onboarded once too. Now I help others get it.", "Tôi cũng từng được onboard. Giờ tôi giúp người khác hiểu."),
    ("Everyday English isn't perfect — but you get by, get better, and get heard.", "Tiếng Anh hàng ngày không hoàn hảo — nhưng bạn xoay xở, tiến bộ, và được lắng nghe."),
]

GET_SENTENCE_VI: dict[str, str] = {
    _normalize_match(en): vi for en, vi in _RAW_SENTENCE_PAIRS
}

GET_PHRASE_NOTES: dict[str, str] = {
    "get looped in": "được thêm vào kênh Slack/email/meeting",
    "getting pinged": "đang bị ping / tag liên tục",
    "get pinged": "bị nhắn / bị tag trên Slack",
    "get up to speed": "nắm bắt nhanh tình hình",
    "getting up to speed": "đang nắm bắt dần",
    "get buy-in": "được đồng thuận từ stakeholder",
    "buy-in": "sự đồng thuận / chấp thuận",
    "get aligned": "thống nhất / cùng hướng",
    "not aligned": "chưa thống nhất",
    "get the ball rolling": "bắt đầu / khởi động việc",
    "get blocked": "bị kẹt vì phụ thuộc",
    "blocked on": "bị chặn ở (dependency/API)",
    "get unblocked": "được gỡ kẹt / tiếp tục được",
    "get through": "vượt qua / hoàn thành (review, buổi học)",
    "code review": "xem xét PR trước khi merge",
    "get shipped": "được deploy lên production",
    "got shipped": "đã được ship (V3 — trạng thái kết quả)",
    "get sign-off": "được phê duyệt chính thức",
    "sign-off": "phê duyệt chính thức",
    "get ready": "chuẩn bị sẵn sàng",
    "get pulled into": "bị kéo vào (war room / sự cố)",
    "get stuck": "bị kẹt / bí — không tiến triển",
    "get back to": "phản hồi lại / quay lại việc",
    "get face time": "có thời gian trực tiếp với leadership",
    "get promoted": "được thăng chức",
    "getting acquired": "đang bị mua lại (công ty)",
    "get acquired": "bị mua lại",
    "get to": "đến (một nơi)",
    "get checked in": "làm xong thủ tục nhận phòng",
    "get your bearings": "định hướng / nắm vị trí xung quanh",
    "get my bearings": "định hướng được (của tôi)",
    "get a ticket": "mua vé",
    "get on": "lên (tàu / xe) — không dùng *get in the train*",
    "get off": "xuống (tàu / xe) tại ga",
    "get a view of": "nhìn thấy / ngắm cảnh",
    "altitude sickness": "say độ cao",
    "get change": "đổi tiền lẻ",
    "get snowed in": "bị kẹt vì tuyết",
    "got held up": "bị trì hoãn / chậm lại",
    "get held up": "bị trì hoãn",
    "get by": "xoay xở được / tạm đủ dùng",
    "gets you by": "giúp bạn xoay xở được",
    "get lost": "bị lạc",
    "get swept up in": "bị cuốn vào (sự kiện / không khí)",
    "get around": "đi lại quanh khu vực",
    "get used to": "quen dần với",
    "not used to": "chưa quen với",
    "get it": "hiểu rồi / nắm được",
    "get onboarded": "được hướng dẫn nhập môn / làm quen hệ thống",
    "get a ride": "được chở / nhờ xe",
    "stakeholders": "các bên liên quan cần được cập nhật",
    "standup": "họp standup hàng ngày (Scrum)",
    "dependency": "phụ thuộc kỹ thuật — chặn tiến độ",
    "staging": "môi trường staging (gần giống production)",
    "war room": "phòng xử lý sự cố khẩn cấp",
    "rollback": "hoàn tác bản deploy",
}

GET_GRAMMAR_PATTERNS: list[tuple[str, str]] = [
    (r"\bget looped in\b", "**get looped in on + topic** = được thêm vào luồng — cần **-ed** (looped)."),
    (r"\bgetting pinged\b|\bget pinged\b", "**get pinged** = bị tag/nhắn liên tục trên Slack."),
    (r"\bget up to speed\b|\bgetting up to speed\b", "**get up to speed on + topic** = nắm bắt nhanh tình hình."),
    (r"\bget buy-in\b|\bbuy-in\b", "**get buy-in from + team** = được đồng thuận trước khi ship."),
    (r"\bget aligned\b|\bnot aligned\b", "**get aligned on + topic** = thống nhất hướng đi."),
    (r"\bget the ball rolling\b", "**get the ball rolling** = idiom — bắt đầu / khởi động việc."),
    (r"\bget blocked\b|\bblocked on\b", "**be/get blocked on + noun** = bị kẹt vì phụ thuộc/API."),
    (r"\bget unblocked\b|\bbe unblocked\b", "**get/be unblocked** = được gỡ chướng ngại, tiếp tục làm."),
    (r"\bget through\b|\bgot through\b", "**get through + noun** = vượt qua giai đoạn (review, buổi học)."),
    (r"\bget shipped\b|\bgot shipped\b", "**get + V3 (shipped)** = feature đã lên production."),
    (r"\bget sign-off\b|\bsign-off\b", "**get sign-off from + person/team** = được phê duyệt chính thức."),
    (r"\bget ready\b", "**get + adj (ready)** = trở nên sẵn sàng."),
    (r"\bget pulled into\b|\bgetting pulled into\b", "**get pulled into + noun** = bị kéo vào sự cố/meeting khẩn."),
    (r"\bget stuck\b|\bi'm stuck\b", "**get/be stuck** = bí / không tiến triển."),
    (r"\bget back to\b", "**get back to + person** = phản hồi lại sau (email/Slack)."),
    (r"\bget face time\b|\bgot face time\b", "**get face time with + person** = có thời gian trực tiếp với sếp."),
    (r"\bget promoted\b|\bgetting promoted\b", "**get promoted to + role** = được thăng chức."),
    (r"\bget acquired\b|\bgetting acquired\b", "**get acquired** = (công ty) bị mua lại."),
    (r"\bget to\b", "**get to + place** = đến nơi — không bỏ *to*."),
    (r"\bget checked in\b", "**get checked in** = làm xong thủ tục nhận phòng."),
    (r"\bget your bearings\b|\bget my bearings\b", "**get your bearings** = định hướng sau khi đến nơi mới."),
    (r"\bget a ticket\b", "**get a ticket** = mua vé (kèm reservation nếu cần)."),
    (r"\bget on\b", "**get on + vehicle** = lên tàu/xe — *get on the train*, không *get in the train*."),
    (r"\bget off\b", "**get off at + place** = xuống tại ga/điểm dừng."),
    (r"\bget a view of\b|\bgot a view of\b", "**get a view of + cảnh** = nhìn thấy toàn cảnh."),
    (r"\baltitude sickness\b|\bgetting altitude sickness\b", "**get altitude sickness** = bị say độ cao."),
    (r"\bget change\b", "**get change for + bill** = đổi tiền lẻ."),
    (r"\bget snowed in\b", "**get snowed in** = bị kẹt vì tuyết, không ra được."),
    (r"\bgot held up\b|\bgetting held up\b", "**get held up by + reason** = bị trì hoãn."),
    (r"\bget by\b|\bgets you by\b", "**get by (with + X)** = xoay xở được với ít tài nguyên."),
    (r"\bget lost\b|\bwe're lost\b", "**get lost** = bị lạc."),
    (r"\bget swept up in\b|\bgot swept up in\b", "**get swept up in + event** = bị cuốn vào sự kiện/không khí."),
    (r"\bget around\b", "**get around** = đi lại quanh khu vực."),
    (r"\bget used to\b|\bnot used to\b", "**get used to + V-ing** = quen dần — khác *used to + V* (trước đây hay làm)."),
    (r"\bget it\b|\bi get it\b", "**get it** = hiểu rồi! (thân mật)."),
    (r"\bget onboarded\b|\bget you onboarded\b", "**get onboarded** = được hướng dẫn nhập môn công ty."),
    (r"\bget a ride\b", "**get a ride to + place** = được chờ đến nơi."),
    (r"\bkeep getting\b", "**keep + V-ing** = cứ liên tục làm / bị (keep getting pinged)."),
]
